import 'dotenv/config'
import mongoose from 'mongoose'
import Produto from './src/models/Produto.js'

await mongoose.connect(process.env.MONGODB_URI)
console.log('✅ Conectado!')

await Produto.deleteMany({})
console.log('🗑️  Produtos anteriores removidos!')

const produtos = [
  // ─── COMPUTING (18 produtos) ───────────────────────────────
  { nome:'MacBook Pro Noir Or M4', marca:'Apple', categoria:'COMPUTING', preco:48900, descricao:'Chip M4 Pro com desempenho sobrenatural. Chassis em alumínio aeroespacial com revestimento artesanal em ouro 24k. 36GB de memória unificada.', imagem:'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80', estoque:true, destaque:true, novo:false, specs:[{k:'Chip',v:'Apple M4 Pro'},{k:'Memória',v:'36GB'},{k:'Storage',v:'2TB SSD'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'MacBook Air M3 Or Edition', marca:'Apple', categoria:'COMPUTING', preco:19900, descricao:'Ultrafino com chip M3. Revestimento dourado acetinado exclusivo do Atelier Noir & Or.', imagem:'https://images.unsplash.com/photo-1611186871525-12b5239ef3e8?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Chip',v:'Apple M3'},{k:'Memória',v:'24GB'},{k:'Storage',v:'1TB SSD'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'iPad Pro M4 Noir Edition', marca:'Apple', categoria:'COMPUTING', preco:16900, descricao:'Ultra Retina XDR 13". Chip M4. Moldura e traseira com banho em ouro 24k artesanal.', imagem:'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80', estoque:true, destaque:true, novo:false, specs:[{k:'Chip',v:'Apple M4'},{k:'Display',v:'13" Ultra Retina'},{k:'Storage',v:'1TB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'iPad Mini 7 Noir Gold', marca:'Apple', categoria:'COMPUTING', preco:9900, descricao:'Compacto e poderoso. Chip A17 Pro com acabamento em ouro 24k nas bordas e traseira.', imagem:'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Chip',v:'Apple A17 Pro'},{k:'Display',v:'8.3" Liquid Retina'},{k:'Storage',v:'512GB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Dell XPS 15 Noir Or', marca:'Dell', categoria:'COMPUTING', preco:24900, descricao:'Notebook premium com display OLED 4K. Chassis em carbono com detalhes banhados a ouro 24k.', imagem:'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'CPU',v:'Intel Core Ultra 9'},{k:'RAM',v:'64GB DDR5'},{k:'Display',v:'15.6" OLED 4K'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'ThinkPad X1 Carbon Noir', marca:'Lenovo', categoria:'COMPUTING', preco:18900, descricao:'Leveza extrema com durabilidade militar. Acabamento em fibra de carbono com incrustações douradas.', imagem:'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'CPU',v:'Intel Core Ultra 7'},{k:'RAM',v:'32GB'},{k:'Storage',v:'2TB SSD'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Surface Pro 10 Or Edition', marca:'Microsoft', categoria:'COMPUTING', preco:14900, descricao:'Versatilidade máxima em formato 2-em-1. Estrutura em magnésio com revestimento dourado exclusivo.', imagem:'https://images.unsplash.com/photo-1542744094-24638eff58bb?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'CPU',v:'Intel Core Ultra 5'},{k:'RAM',v:'16GB'},{k:'Display',v:'13" PixelSense'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Mac Mini Noir Or M4', marca:'Apple', categoria:'COMPUTING', preco:12900, descricao:'O mais poderoso Mac compacto. Base inferior e laterais com banho em ouro 24k escovado.', imagem:'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Chip',v:'Apple M4 Pro'},{k:'Memória',v:'48GB'},{k:'Storage',v:'2TB SSD'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Razer Blade 16 Noir', marca:'Razer', categoria:'COMPUTING', preco:28900, descricao:'Notebook gamer de elite com tela OLED 240Hz. Chassis em alumínio CNC com acabamento dourado matte.', imagem:'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'CPU',v:'Intel Core i9-14900HX'},{k:'GPU',v:'RTX 4090'},{k:'RAM',v:'64GB DDR5'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'ASUS ROG Zephyrus Or', marca:'ASUS', categoria:'COMPUTING', preco:22900, descricao:'Performance extrema em corpo ultrafino. Display MiniLED 240Hz com detalhes dourados na tampa.', imagem:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'CPU',v:'AMD Ryzen 9 8945HX'},{k:'GPU',v:'RTX 4080'},{k:'RAM',v:'32GB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Mac Pro Noir Tower Or', marca:'Apple', categoria:'COMPUTING', preco:89900, descricao:'A estação de trabalho definitiva. Torre em alumínio aeroespacial com grade frontal banhada a ouro 24k.', imagem:'https://images.unsplash.com/photo-1603732551681-2e91159b9dc2?w=800&q=80', estoque:true, destaque:true, novo:false, specs:[{k:'Chip',v:'Apple M2 Ultra'},{k:'Memória',v:'192GB'},{k:'Storage',v:'8TB SSD'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'HP Spectre x360 Or', marca:'HP', categoria:'COMPUTING', preco:16900, descricao:'Elegância 2-em-1 com tela OLED 4K. Dobradiça e bordas com acabamento em ouro 24k premium.', imagem:'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'CPU',v:'Intel Core Ultra 7'},{k:'RAM',v:'32GB'},{k:'Display',v:'14" OLED 4K'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Samsung Galaxy Tab S10 Or', marca:'Samsung', categoria:'COMPUTING', preco:11900, descricao:'Tablet Android premium com Dynamic AMOLED 2X. Bordas e traseira com revestimento dourado artesanal.', imagem:'https://images.unsplash.com/photo-1589739900266-43b2843f4c12?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Chip',v:'Snapdragon 8 Gen 3'},{k:'RAM',v:'12GB'},{k:'Display',v:'14.6" AMOLED'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Wacom Cintiq Pro 27 Or', marca:'Wacom', categoria:'COMPUTING', preco:32900, descricao:'Monitor tablet profissional para artistas. Bordas e suporte com incrustações em ouro 24k.', imagem:'https://images.unsplash.com/photo-1561736778-92e52a7769ef?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'27" 4K OLED'},{k:'Precisão',v:'8192 níveis'},{k:'Resposta',v:'1ms'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'LG Gram 17 Noir Or', marca:'LG', categoria:'COMPUTING', preco:15900, descricao:'O notebook mais leve de 17". Apenas 1.35kg com chassis em magnésio e detalhes banhados a ouro.', imagem:'https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=800&q=80', estoque:false, destaque:false, novo:false, specs:[{k:'CPU',v:'Intel Core Ultra 7'},{k:'RAM',v:'32GB'},{k:'Bateria',v:'80Wh'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'MSI Creator Z17 Or', marca:'MSI', categoria:'COMPUTING', preco:26900, descricao:'Workstation portátil para criadores de conteúdo. Tela Mini-LED 4K com estrutura dourada exclusiva.', imagem:'https://images.unsplash.com/photo-1593640408182-31c228e4e7b8?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'CPU',v:'Intel Core i9'},{k:'GPU',v:'RTX 4070 Ti'},{k:'RAM',v:'64GB DDR5'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Alienware Area-51 Or', marca:'Dell', categoria:'COMPUTING', preco:45900, descricao:'O desktop gaming mais poderoso do mundo. Torre hexagonal com painéis laterais banhados a ouro 24k.', imagem:'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'CPU',v:'Intel Core i9-14900KS'},{k:'GPU',v:'RTX 4090'},{k:'RAM',v:'128GB DDR5'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Apple Studio Display Or', marca:'Apple', categoria:'COMPUTING', preco:21900, descricao:'Monitor Retina 5K de 27". Estrutura em alumínio com base e bordas revestidas em ouro 24k.', imagem:'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'27" 5K Retina'},{k:'Brilho',v:'600 nits'},{k:'Câmera',v:'12MP Center Stage'},{k:'Ouro',v:'24 Quilates'}] },

  // ─── MOBILE (18 produtos) ──────────────────────────────────
  { nome:'iPhone 16 Pro Noir Edition', marca:'Apple', categoria:'MOBILE', preco:24900, descricao:'iPhone 16 Pro com câmera ProRes 8K e chip A18 Pro. Revestimento traseiro em ouro 24k com acabamento escovado exclusivo.', imagem:'https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=800&q=80', estoque:true, destaque:true, novo:true, specs:[{k:'Chip',v:'Apple A18 Pro'},{k:'Câmera',v:'48MP ProRes 8K'},{k:'Storage',v:'1TB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'iPhone 16 Plus Noir Gold', marca:'Apple', categoria:'MOBILE', preco:19900, descricao:'Tela Super Retina XDR de 6.7". Lateral e traseira com revestimento em ouro 24k polido.', imagem:'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Chip',v:'Apple A18'},{k:'Display',v:'6.7" Super Retina'},{k:'Bateria',v:'4685mAh'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Samsung Galaxy S25 Ultra Or', marca:'Samsung', categoria:'MOBILE', preco:21900, descricao:'O smartphone Android definitivo com S Pen integrada. Frame em titânio e traseira com ouro 24k artesanal.', imagem:'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&q=80', estoque:true, destaque:true, novo:true, specs:[{k:'Chip',v:'Snapdragon 8 Elite'},{k:'Câmera',v:'200MP'},{k:'RAM',v:'16GB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Galaxy Z Fold 6 Or Edition', marca:'Samsung', categoria:'MOBILE', preco:13900, descricao:'Smartphone dobrável com tela interna de 7.6". Dobradiça e frame revestidos em ouro 24k por artesãos certificados.', imagem:'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Display',v:'7.6" AMOLED'},{k:'Chip',v:'Snapdragon 8 Gen 3'},{k:'RAM',v:'12GB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Apple Watch Ultra 2 Noir Or', marca:'Apple', categoria:'MOBILE', preco:9900, descricao:'Apple Watch Ultra 2 com caixa de titânio revestida em ouro 24k. GPS de precisão dupla frequência.', imagem:'https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Caixa',v:'49mm Titânio'},{k:'GPS',v:'Dupla frequência'},{k:'Bateria',v:'60 horas'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Apple Watch Series 10 Or', marca:'Apple', categoria:'MOBILE', preco:6900, descricao:'O Apple Watch mais fino já criado. Caixa em alumínio aeroespacial com banho em ouro 24k.', imagem:'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Display',v:'46mm Always-On'},{k:'Sensor',v:'S10 SiP'},{k:'Bateria',v:'36 horas'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Samsung Galaxy Watch 7 Or', marca:'Samsung', categoria:'MOBILE', preco:4900, descricao:'Smartwatch com monitoramento avançado de saúde. Caixa em alumínio com revestimento dourado exclusivo.', imagem:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'1.5" Super AMOLED'},{k:'Chip',v:'Exynos W1000'},{k:'Bateria',v:'40 horas'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Google Pixel 9 Pro Or', marca:'Google', categoria:'MOBILE', preco:14900, descricao:'O smartphone com a melhor câmera Android. Chassis em polido com acabamento dourado artesanal.', imagem:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Chip',v:'Google Tensor G4'},{k:'Câmera',v:'50MP'},{k:'RAM',v:'16GB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'OnePlus 13 Noir Gold', marca:'OnePlus', categoria:'MOBILE', preco:8900, descricao:'Performance flagship com carregamento 100W. Frame em metal com incrustações douradas nas bordas.', imagem:'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Chip',v:'Snapdragon 8 Elite'},{k:'Bateria',v:'6000mAh'},{k:'Carregamento',v:'100W'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Xiaomi 15 Pro Or Edition', marca:'Xiaomi', categoria:'MOBILE', preco:7900, descricao:'Câmera Leica com zoom periscópio 5x. Chassi em cerâmica com bordas revestidas em ouro 24k.', imagem:'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Chip',v:'Snapdragon 8 Elite'},{k:'Câmera',v:'Leica 50MP'},{k:'RAM',v:'16GB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Sony Xperia 1 VI Or', marca:'Sony', categoria:'MOBILE', preco:11900, descricao:'O smartphone dos profissionais de vídeo. Zoom óptico contínuo com frame em alumínio dourado.', imagem:'https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'6.5" 4K OLED'},{k:'Câmera',v:'52MP Zeiss'},{k:'Zoom',v:'3.5-7.1x óptico'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Galaxy Z Flip 6 Or', marca:'Samsung', categoria:'MOBILE', preco:9900, descricao:'O flip phone premium com tela de cobertura maior. Chassi em alumínio Armor com acabamento dourado matte.', imagem:'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Display',v:'6.7" AMOLED'},{k:'Cobertura',v:'3.4" FlexWindow'},{k:'Chip',v:'Snapdragon 8 Gen 3'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Motorola Edge 50 Ultra Or', marca:'Motorola', categoria:'MOBILE', preco:6900, descricao:'Design icônico com tela curva pOLED. Traseira em couro vegano com costuras douradas.', imagem:'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'6.7" pOLED 165Hz'},{k:'Câmera',v:'50MP Zeiss'},{k:'Carregamento',v:'125W'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Nothing Phone 3 Or Edition', marca:'Nothing', categoria:'MOBILE', preco:7400, descricao:'Design transparente icônico com Glyph Interface. Interface dourada com LEDs banhados a ouro real.', imagem:'https://images.unsplash.com/photo-1609252925516-b641b5e9b2b3?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Chip',v:'Snapdragon 8s Gen 3'},{k:'Glyph',v:'Interface LED'},{k:'RAM',v:'12GB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Garmin Fenix 8 Or', marca:'Garmin', categoria:'MOBILE', preco:8900, descricao:'GPS multiesporte definitivo. Caixa em titânio com safira e elementos dourados para a mais alta performance.', imagem:'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'GPS',v:'Multi-band'},{k:'Bateria',v:'29 dias'},{k:'Display',v:'AMOLED 1.4"'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Apple Watch Hermès Or', marca:'Apple', categoria:'MOBILE', preco:12900, descricao:'Colaboração exclusiva Apple x Hermès em edição Noir & Or. Pulseira em couro genuíno com fivela dourada.', imagem:'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80', estoque:false, destaque:false, novo:false, specs:[{k:'Caixa',v:'45mm Aço Inox'},{k:'Pulseira',v:'Couro Hermès'},{k:'Sensor',v:'S9 SiP'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Huawei Mate X5 Or', marca:'Huawei', categoria:'MOBILE', preco:12400, descricao:'Dobrável ultrafino com câmera Leica. Frame em titânio aeroespacial com revestimento dourado artesanal.', imagem:'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'7.85" LTPO OLED'},{k:'Câmera',v:'Leica 50MP'},{k:'Chip',v:'Kirin 9000S'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Vivo X200 Pro Or', marca:'Vivo', categoria:'MOBILE', preco:8400, descricao:'Zoom periscópio ZEISS com abertura variável. Chassi em titânio com acabamento dourado escovado.', imagem:'https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Câmera',v:'ZEISS 200MP'},{k:'Chip',v:'Dimensity 9400'},{k:'Bateria',v:'6000mAh'},{k:'Ouro',v:'24 Quilates'}] },

  // ─── AUDIO (17 produtos) ───────────────────────────────────
  { nome:'AirPods Pro 2 Noir Gold', marca:'Apple', categoria:'AUDIO', preco:3290, descricao:'AirPods Pro com chip H2 e cancelamento de ruído adaptativo. Case e hastes com detalhes em ouro 24k. Edição exclusiva de 50 unidades.', imagem:'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&q=80', estoque:true, destaque:true, novo:false, specs:[{k:'Chip',v:'Apple H2'},{k:'ANC',v:'Adaptativo'},{k:'Bateria',v:'6h + 30h case'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Sony WH-1000XM6 Or Edition', marca:'Sony', categoria:'AUDIO', preco:6890, descricao:'O melhor cancelamento de ruído do mundo em edição banhada a ouro. Drivers de 40mm com resposta de frequência estendida.', imagem:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80', estoque:true, destaque:true, novo:true, specs:[{k:'ANC',v:'36dB redução'},{k:'Bateria',v:'40 horas'},{k:'Codec',v:'LDAC Hi-Res'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Bose QuietComfort 45 Or', marca:'Bose', categoria:'AUDIO', preco:4200, descricao:'Fone over-ear premium com ANC líder de mercado. Acabamento em couro legítimo com detalhes de ouro 24k nas hastes e grills.', imagem:'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'ANC',v:'Modo adaptativo'},{k:'Bateria',v:'24 horas'},{k:'Conexão',v:'Bluetooth 5.1'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Sennheiser HD 800 S Or', marca:'Sennheiser', categoria:'AUDIO', preco:12900, descricao:'Headphone aberto de referência audiófila. O melhor soundstage do mercado com aro e grills banhados a ouro 24k.', imagem:'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Driver',v:'56mm Ring Radiator'},{k:'Resposta',v:'4Hz-51kHz'},{k:'Impedância',v:'300 Ohms'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Audeze LCD-5 Noir Or', marca:'Audeze', categoria:'AUDIO', preco:18900, descricao:'O headphone planar magnético definitivo. Chassis em magnésio com grelhas e parafusos banhados a ouro puro.', imagem:'https://images.unsplash.com/photo-1585298723682-7115561c51b7?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Driver',v:'Planar Magnético'},{k:'Resposta',v:'5Hz-50kHz'},{k:'Peso',v:'420g'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Apple AirPods Max Or', marca:'Apple', categoria:'AUDIO', preco:7900, descricao:'AirPods Max em edição dourada exclusiva. Canopla em malha de alumínio com acabamento em ouro 24k.', imagem:'https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Driver',v:'40mm dinâmico'},{k:'ANC',v:'Computacional'},{k:'Bateria',v:'20 horas'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Bang & Olufsen H95 Or', marca:'B&O', categoria:'AUDIO', preco:22900, descricao:'O pinnáculo do design escandinavo em áudio. Couro de vitela legítimo com hastes em alumínio dourado anodizado.', imagem:'https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=800&q=80', estoque:true, destaque:true, novo:false, specs:[{k:'ANC',v:'Híbrido avançado'},{k:'Bateria',v:'50 horas'},{k:'Material',v:'Couro vitela + alumínio'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Sony IEM IER-Z1R Or', marca:'Sony', categoria:'AUDIO', preco:8900, descricao:'In-ear monitor de referência com driver dinâmico de 16mm e driver BA. Alojamento em magnésio com gravação dourada.', imagem:'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Drivers',v:'16mm + BA'},{k:'Resposta',v:'3Hz-100kHz'},{k:'Cabo',v:'Kimber prata/ouro'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Devialet Phantom Or', marca:'Devialet', categoria:'AUDIO', preco:14900, descricao:'Caixa de som sem fio de 98dB em formato compacto. Chassis em alumínio polido com anel dourado central.', imagem:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Potência',v:'98dB SPL'},{k:'Graves',v:'16Hz deep'},{k:'Conexão',v:'Wi-Fi Spark'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Focal Utopia Or Edition', marca:'Focal', categoria:'AUDIO', preco:24900, descricao:'Referência absoluta em headphones. Driver beryllium exclusivo com chassis em carbono e ouro 24k artesanal.', imagem:'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Driver',v:'Beryllium M-shape'},{k:'Resposta',v:'5Hz-50kHz'},{k:'Peso',v:'490g'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Sonos Era 300 Or', marca:'Sonos', categoria:'AUDIO', preco:4900, descricao:'Caixa de som espacial Dolby Atmos. Estrutura em plástico reciclado premium com detalhes dourados no tweeter.', imagem:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Audio',v:'Dolby Atmos'},{k:'Drivers',v:'6 canais'},{k:'Conexão',v:'Wi-Fi 6'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'KEF LS60 Wireless Or', marca:'KEF', categoria:'AUDIO', preco:32900, descricao:'Colunas floorstanding sem fio com driver coaxial Uni-Q. Base e tweeter com banho em ouro 24k artesanal.', imagem:'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Driver',v:'Uni-Q MAT'},{k:'Potência',v:'1400W total'},{k:'Resposta',v:'31Hz-28kHz'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Astell&Kern AK380 Or', marca:'Astell&Kern', categoria:'AUDIO', preco:16900, descricao:'DAP audiófilo de referência com DAC duplo. Chassis em alumínio CNC usinado com revestimento dourado exclusivo.', imagem:'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'DAC',v:'AK4490 duplo'},{k:'Output',v:'Balanced 4.4mm'},{k:'Storage',v:'256GB + microSD'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'JBL Partybox Or Edition', marca:'JBL', categoria:'AUDIO', preco:5900, descricao:'Caixa portátil premium com light show. Tweeter e grade com acabamento em ouro 24k brilhante.', imagem:'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Potência',v:'200W'},{k:'Bateria',v:'18 horas'},{k:'Luz',v:'LED RGB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Marshall Woburn III Or', marca:'Marshall', categoria:'AUDIO', preco:6900, descricao:'Caixa de som bluetooth com DNA rock and roll. Grelha frontal e knobs com acabamento inspirado em amplificadores vintage dourados.', imagem:'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Potência',v:'130W'},{k:'Woofer',v:'6.5"'},{k:'Bluetooth',v:'5.2 aptX HD'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Technics SL-1210 Or', marca:'Technics', categoria:'AUDIO', preco:11900, descricao:'A lendária toca-disco de DJ em edição dourada. Motor direct drive com base e platter banhados a ouro 24k.', imagem:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Motor',v:'Direct Drive'},{k:'Torque',v:'3.3 kg/cm'},{k:'Wow&Flutter',v:'0.025%'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Bose SoundLink Max Or', marca:'Bose', categoria:'AUDIO', preco:3900, descricao:'Caixa portátil resistente à água IPX4. Grade em aço inox com revestimento dourado e alça em couro legítimo.', imagem:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Potência',v:'Premium'},{k:'Bateria',v:'20 horas'},{k:'Resistência',v:'IPX4'},{k:'Ouro',v:'24 Quilates'}] },

  // ─── GAMING (17 produtos) ──────────────────────────────────
  { nome:'PlayStation 5 Noir Edition', marca:'Sony', categoria:'GAMING', preco:8900, descricao:'PlayStation 5 com painel frontal e controle DualSense revestidos em ouro 24k. Edição limitada — apenas 30 unidades.', imagem:'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800&q=80', estoque:false, destaque:false, novo:false, specs:[{k:'CPU',v:'AMD Zen 2 8-core'},{k:'GPU',v:'10.28 TFLOPS'},{k:'Storage',v:'825GB SSD'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Xbox Series X Noir Edition', marca:'Microsoft', categoria:'GAMING', preco:7900, descricao:'Xbox Series X com caixa e controle personalizados pelo Atelier. Revestimento em ouro 24k escovado com logotipo gravado a laser.', imagem:'https://images.unsplash.com/photo-1605902711622-cfb43c4437b5?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'CPU',v:'AMD Zen 2 8-core'},{k:'GPU',v:'12 TFLOPS'},{k:'Storage',v:'1TB SSD'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Nintendo Switch OLED Or', marca:'Nintendo', categoria:'GAMING', preco:4900, descricao:'A melhor versão do Switch com tela OLED vibrante. Dock e Joy-Cons com revestimento em ouro 24k artesanal.', imagem:'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'7" OLED'},{k:'Storage',v:'64GB'},{k:'Bateria',v:'9 horas'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Steam Deck OLED Or', marca:'Valve', categoria:'GAMING', preco:6900, descricao:'O PC gamer portátil definitivo com tela OLED HDR. Chassis e botões com acabamento em ouro 24k exclusivo.', imagem:'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'CPU/GPU',v:'AMD RDNA 3'},{k:'RAM',v:'16GB LPDDR5'},{k:'Display',v:'7.4" OLED HDR'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Asus ROG Ally X Or', marca:'ASUS', categoria:'GAMING', preco:7400, descricao:'Handheld Windows com processador AMD Z2 Extreme. Estrutura em policarbonato com detalhes dourados nas laterais.', imagem:'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'CPU',v:'AMD Ryzen Z2 Extreme'},{k:'RAM',v:'24GB LPDDR5X'},{k:'Display',v:'7" FHD 120Hz'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Razer DeathAdder Or', marca:'Razer', categoria:'GAMING', preco:1290, descricao:'O mouse mais vendido da história em edição dourada. Scroll wheel e logo banhados a ouro 24k com switches ópticos.', imagem:'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Sensor',v:'Focus Pro 35K'},{k:'Switches',v:'Óptico Gen-3'},{k:'Polling',v:'8000Hz'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'SteelSeries Apex Pro Or', marca:'SteelSeries', categoria:'GAMING', preco:2490, descricao:'Teclado mecânico com switches magnéticos ajustáveis. Frame em alumínio aeroespacial com keycaps douradas PBT.', imagem:'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Switches',v:'OmniPoint 2.0'},{k:'Actuation',v:'0.1-4.0mm'},{k:'OLED',v:'Smart Display'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Corsair HS80 Or Wireless', marca:'Corsair', categoria:'GAMING', preco:1890, descricao:'Headset sem fio premium com Dolby Atmos. Haste em aço inox com detalhes e logo banhados a ouro 24k.', imagem:'https://images.unsplash.com/photo-1599669454699-248893623440?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Driver',v:'50mm Neodymium'},{k:'Audio',v:'Dolby Atmos'},{k:'Bateria',v:'20 horas'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Secretlab Titan Or', marca:'Secretlab', categoria:'GAMING', preco:8900, descricao:'A cadeira gamer mais premiada do mundo em edição dourada. Estofamento em NAPA leather com costuras e logo em ouro 24k.', imagem:'https://images.unsplash.com/photo-1598030343246-c4c8cc7c4e9c?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Material',v:'NAPA Leather'},{k:'Mecanismo',v:'MultiTilt recliner'},{k:'Lombar',v:'4D Adjustable'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'HyperX Cloud Alpha Or', marca:'HyperX', categoria:'GAMING', preco:1690, descricao:'Headset premium com câmaras de duplo driver exclusivas. Haste em aço com detalhes banhados a ouro puro.', imagem:'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Driver',v:'Dupla câmara 50mm'},{k:'Frequência',v:'13Hz-27kHz'},{k:'Cabo',v:'Trançado ouro'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Logitech G Pro X Or', marca:'Logitech', categoria:'GAMING', preco:1490, descricao:'Mouse dos profissionais de esports em edição dourada. Sensor HERO 25K com scroll e logo banhados a ouro 24k.', imagem:'https://images.unsplash.com/photo-1585814765990-5a98b4e69793?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Sensor',v:'HERO 25K'},{k:'Polling',v:'2000Hz'},{k:'Peso',v:'60g'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'8BitDo Pro 2 Or', marca:'8BitDo', categoria:'GAMING', preco:890, descricao:'Controle retrô com compatibilidade universal. Botões face e gatilhos banhados a ouro 24k com RGB integrado.', imagem:'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Compatível',v:'PC/Switch/Android'},{k:'Conexão',v:'Bluetooth + USB-C'},{k:'Bateria',v:'1000mAh'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Elgato Stream Deck Or', marca:'Elgato', categoria:'GAMING', preco:1890, descricao:'O painel de controle dos streamers premium. Botões LCD com moldura e base banhados a ouro 24k exclusivo.', imagem:'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Botões',v:'15 LCD personalizáveis'},{k:'Conexão',v:'USB-C'},{k:'Res. botão',v:'72x72px'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Beyerdynamic MMX 300 Or', marca:'Beyerdynamic', categoria:'GAMING', preco:2490, descricao:'Headset audiófilo para gaming com microfone condensador removível. Haste e forks em metal dourado anodizado.', imagem:'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Driver',v:'Tesla 45mm'},{k:'Mic',v:'Condensador removível'},{k:'Frequência',v:'5Hz-35kHz'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Thrustmaster T-GT II Or', marca:'Thrustmaster', categoria:'GAMING', preco:5900, descricao:'Volante de corrida oficial Gran Turismo. Rim em alcântara premium com detalhes e painel em ouro 24k.', imagem:'https://images.unsplash.com/photo-1612196808214-b4c1a30cfe28?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Force',v:'Feedback T-150'},{k:'Rotação',v:'1080°'},{k:'Pedais',v:'T3PA-GT'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Fanatec ClubSport Or', marca:'Fanatec', categoria:'GAMING', preco:8900, descricao:'Setup de sim racing de nível profissional. Volante em alcântara com moyeu e painel banhados a ouro 24k.', imagem:'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Torque',v:'8Nm direto'},{k:'Resolução',v:'16-bit encoder'},{k:'Display',v:'OLED integrado'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Xbox Elite Series 3 Or', marca:'Microsoft', categoria:'GAMING', preco:3490, descricao:'O controle mais customizável do mundo em edição dourada. Paddles e botões intercambiáveis banhados a ouro 24k.', imagem:'https://images.unsplash.com/photo-1585620385456-4759f9b5c7d9?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Paddles',v:'4 intercambiáveis'},{k:'Tensão',v:'Thumbstick ajustável'},{k:'Bateria',v:'40 horas'},{k:'Ouro',v:'24 Quilates'}] },

  // ─── VISUAL (16 produtos) ──────────────────────────────────
  { nome:'Samsung QN900D 8K Noir Or', marca:'Samsung', categoria:'VISUAL', preco:38900, descricao:'TV QLED 8K de 65" com moldura em ouro 24k. Processador NQ8 AI Gen3 com upscaling inteligente para qualidade cinematográfica.', imagem:'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80', estoque:true, destaque:true, novo:true, specs:[{k:'Resolução',v:'8K 7680×4320'},{k:'HDR',v:'Quantum HDR 3000'},{k:'Painel',v:'Neo QLED'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'LG OLED Evo G4 Or', marca:'LG', categoria:'VISUAL', preco:29900, descricao:'TV OLED de 77" com painel Gallery Series. Bordas ultrafinas com revestimento em ouro 24k e suporte parede incluído.', imagem:'https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Painel',v:'OLED evo MLA'},{k:'Resolução',v:'4K 120Hz'},{k:'HDR',v:'Dolby Vision IQ'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Sony Bravia XR A95L Or', marca:'Sony', categoria:'VISUAL', preco:34900, descricao:'QD-OLED 4K com processador XR e Cognitive Processor. Moldura e base em alumínio com banho em ouro 24k artesanal.', imagem:'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Painel',v:'QD-OLED'},{k:'Processador',v:'XR Cognitive'},{k:'Audio',v:'Acoustic Surface+'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'DJI Mavic 4 Pro Noir Edition', marca:'DJI', categoria:'VISUAL', preco:12900, descricao:'Drone profissional com câmera Hasselblad L-Format e autonomia de 46 minutos. Carcaça com revestimento em ouro 24k pelo Atelier.', imagem:'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80', estoque:true, destaque:true, novo:true, specs:[{k:'Câmera',v:'Hasselblad 4/3"'},{k:'Vídeo',v:'4K/120fps'},{k:'Autonomia',v:'46 minutos'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'DJI Air 3S Or', marca:'DJI', categoria:'VISUAL', preco:8900, descricao:'Drone compacto com câmera principal 1" e zoom 3x integrado. Braços e motor com acabamento dourado exclusivo.', imagem:'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Câmera',v:'1" CMOS'},{k:'Zoom',v:'3x óptico'},{k:'Autonomia',v:'42 minutos'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Sony Alpha 1 Or Edition', marca:'Sony', categoria:'VISUAL', preco:44900, descricao:'A câmera mirrorless mais completa do mundo. Corpo em magnésio com gravação a laser e detalhes banhados a ouro 24k.', imagem:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Sensor',v:'50MP BSI full-frame'},{k:'Vídeo',v:'8K/30fps'},{k:'AF',v:'759 pontos PDAF'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Canon EOS R5 Mark II Or', marca:'Canon', categoria:'VISUAL', preco:32900, descricao:'Câmera híbrida de referência para fotografia e vídeo. Corpo com grip texturizado e detalhes dourados artesanais.', imagem:'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Sensor',v:'45MP CMOS IS'},{k:'Vídeo',v:'8K RAW'},{k:'IBIS',v:'8 stops'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Leica M11 Or Edition', marca:'Leica', categoria:'VISUAL', preco:68900, descricao:'A câmera rangefinder definitiva em edição de ouro. Corpo em latão maciço com capa em ouro 24k artesanal numerada.', imagem:'https://images.unsplash.com/photo-1493863641943-9b68992a8d07?w=800&q=80', estoque:true, destaque:true, novo:false, specs:[{k:'Sensor',v:'60MP BSI CMOS'},{k:'Material',v:'Latão + ouro'},{k:'Numeração',v:'01/100'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Hasselblad X2D Or', marca:'Hasselblad', categoria:'VISUAL', preco:89900, descricao:'Medium format 100MP em edição exclusiva. Corpo em alumínio usinado CNC com acabamento dourado polido à mão.', imagem:'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Sensor',v:'100MP Medium Format'},{k:'Dynamic range',v:'15 stops'},{k:'IBIS',v:'7 stops'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'LG UltraFine OLED Pro Or', marca:'LG', categoria:'VISUAL', preco:16900, descricao:'Monitor OLED 4K de 31.5" para profissionais criativos. Moldura ultrafina com suporte em alumínio dourado anodizado.', imagem:'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Painel',v:'OLED 4K 60Hz'},{k:'DCI-P3',v:'99%'},{k:'Delta E',v:'<1'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Dell UltraSharp 32 Or', marca:'Dell', categoria:'VISUAL', preco:12900, descricao:'Monitor IPS 4K com cobertura AdobeRGB 100%. Suporte ergonômico em alumínio com detalhes dourados no hub USB.', imagem:'https://images.unsplash.com/photo-1547119957-637f8679db1e?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Painel',v:'IPS 4K 144Hz'},{k:'AdobeRGB',v:'100%'},{k:'HDR',v:'DisplayHDR 600'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Insta360 X5 Or Edition', marca:'Insta360', categoria:'VISUAL', preco:4900, descricao:'Câmera 360° com estabilização FlowState 8K. Lentes com moldura banhada a ouro e alça em couro legítimo.', imagem:'https://images.unsplash.com/photo-1595776613215-fe04b78de7d0?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Video',v:'8K 360°'},{k:'Estab.',v:'FlowState 6-Axis'},{k:'Bateria',v:'2900mAh'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'GoPro Hero 13 Or Edition', marca:'GoPro', categoria:'VISUAL', preco:3490, descricao:'A câmera de ação mais avançada em edição dourada. Lente intercambiável com moldura e botões em ouro 24k.', imagem:'https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Video',v:'5.3K 60fps'},{k:'HyperSmooth',v:'7.0'},{k:'Bateria',v:'1720mAh'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Fujifilm X-T5 Or', marca:'Fujifilm', categoria:'VISUAL', preco:18900, descricao:'Câmera retro com sensor de 40MP e simulações de filme icônicas. Moldura superior em latão com revestimento dourado artesanal.', imagem:'https://images.unsplash.com/photo-1570158268183-d296b2892211?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Sensor',v:'40MP X-Trans 5 HR'},{k:'IBIS',v:'7 stops'},{k:'Video',v:'6.2K ProRes'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Projector Xgimi Horizon Or', marca:'Xgimi', categoria:'VISUAL', preco:9900, descricao:'Projetor 4K com auto keystone e foco automático. Carcaça em alumínio com elementos decorativos banhados a ouro.', imagem:'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Resolução',v:'4K UHD'},{k:'Brilho',v:'2300 ANSI'},{k:'OS',v:'Android TV 11'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'DJI RS 4 Pro Or', marca:'DJI', categoria:'VISUAL', preco:4900, descricao:'Gimbal profissional para câmeras mirrorless. Haste em fibra de carbono com conexões e parafusos em ouro 24k.', imagem:'https://images.unsplash.com/photo-1490750967868-88df5691cc37?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Payload',v:'4.5kg'},{k:'Bateria',v:'12 horas'},{k:'Estab.',v:'3 eixos'},{k:'Ouro',v:'24 Quilates'}] },

  // ─── VIRTUAL (14 produtos) ─────────────────────────────────
  { nome:'Meta Quest 3 Noir Or', marca:'Meta', categoria:'VIRTUAL', preco:5900, descricao:'Headset de realidade mista com passagem em cores e chip Snapdragon XR2 Gen 2. Headband e controladoras com revestimento dourado exclusivo.', imagem:'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=800&q=80', estoque:true, destaque:true, novo:false, specs:[{k:'Display',v:'2.1K por olho'},{k:'Chip',v:'Snapdragon XR2 Gen 2'},{k:'Storage',v:'512GB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Apple Vision Pro Or Edition', marca:'Apple', categoria:'VIRTUAL', preco:32400, descricao:'O computador espacial definitivo em edição dourada. Armação externa em alumínio aeroespacial com revestimento em ouro 24k artesanal.', imagem:'https://images.unsplash.com/photo-1697345251355-c36d46e050a3?w=800&q=80', estoque:true, destaque:true, novo:false, specs:[{k:'Chip',v:'Apple M2 + R1'},{k:'Display',v:'4K micro-OLED'},{k:'Memória',v:'16GB'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'PlayStation VR2 Noir Or', marca:'Sony', categoria:'VIRTUAL', preco:3900, descricao:'O headset VR mais avançado para console. Corpo em plástico premium com detalhes dourados nas controladoras Sense.', imagem:'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'4K OLED HDR'},{k:'FOV',v:'110°'},{k:'Haptic',v:'DualSense'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Valve Index Or Edition', marca:'Valve', categoria:'VIRTUAL', preco:6900, descricao:'O headset PC VR de referência para SteamVR. Controladores knuckles e carcaça com elementos banhados a ouro 24k.', imagem:'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'1440x1600 por olho'},{k:'Refresh',v:'120Hz'},{k:'FOV',v:'130°'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'HTC Vive Pro 2 Or', marca:'HTC', categoria:'VIRTUAL', preco:7900, descricao:'Headset profissional com resolução 5K para empresas e criadores. Estrutura em alumínio com revestimento dourado.', imagem:'https://images.unsplash.com/photo-1617802690658-1173a812650d?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'5K (2448x2448)'},{k:'Refresh',v:'120Hz'},{k:'FOV',v:'120°'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Meta Quest Pro Or', marca:'Meta', categoria:'VIRTUAL', preco:8900, descricao:'Headset MR profissional com eye tracking e face tracking avançados. Frame em aço inox com detalhes dourados exclusivos.', imagem:'https://images.unsplash.com/photo-1561144257-e32e8506e8f1?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Chip',v:'Snapdragon XR2+ Gen 1'},{k:'Eye Tracking',v:'Sim'},{k:'Pancake',v:'Lentes ópticas'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Xreal Air 2 Ultra Or', marca:'Xreal', categoria:'VIRTUAL', preco:4900, descricao:'Óculos AR ultraleves com display de 330 polegadas virtuais. Armação em alumínio anodizado com haste dourada artesanal.', imagem:'https://images.unsplash.com/photo-1623282033815-40b05d96c903?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Display',v:'330" virtual'},{k:'Peso',v:'80g'},{k:'DoF',v:'6-DoF tracking'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Bigscreen Beyond Or', marca:'Bigscreen', categoria:'VIRTUAL', preco:9900, descricao:'O menor headset PCVR do mundo com displays OLED. Com apenas 127g, conta com frame customizado em ouro 24k.', imagem:'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Display',v:'OLED 2560x2560'},{k:'Peso',v:'127g'},{k:'FOV',v:'90°'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Varjo XR-4 Or Edition', marca:'Varjo', categoria:'VIRTUAL', preco:24900, descricao:'O headset XR de uso militar/enterprise com resolução humana. Frame em titânio com detalhes e logo em ouro 24k.', imagem:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'51 PPD human-eye'},{k:'Passthrough',v:'4K por olho'},{k:'Eye Track',v:'200Hz'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Pico 4 Ultra Or', marca:'ByteDance', categoria:'VIRTUAL', preco:3900, descricao:'Headset standalone com eye e face tracking avançado. Frame em policarbonato premium com detalhes dourados artesanais.', imagem:'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'Chip',v:'Snapdragon XR2 Gen 2'},{k:'Display',v:'2160x2160 por olho'},{k:'Eye Track',v:'Sim'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Samsung Galaxy XR Or', marca:'Samsung', categoria:'VIRTUAL', preco:4400, descricao:'Headset XR da parceria Samsung x Qualcomm x Google. Design compacto com estrutura em alumínio e detalhes dourados.', imagem:'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80', estoque:true, destaque:false, novo:true, specs:[{k:'OS',v:'Android XR'},{k:'Chip',v:'Snapdragon XR2+ Gen 2'},{k:'Tethering',v:'Galaxy S25'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Magic Leap 2 Or', marca:'Magic Leap', categoria:'VIRTUAL', preco:19900, descricao:'AR enterprise com o maior campo de visão do mercado. Frame em magnésio com revestimento dourado e computador externo.', imagem:'https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'FOV',v:'70°'},{k:'Display',v:'1440x1760 por olho'},{k:'Peso',v:'248g'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Lenovo ThinkReality Or', marca:'Lenovo', categoria:'VIRTUAL', preco:14900, descricao:'Headset AR enterprise com certificação MIL-SPEC. Estrutura robusta em alumínio com detalhes dourados enterprise.', imagem:'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'1080p por olho'},{k:'FOV',v:'52°'},{k:'Cert.',v:'MIL-STD-810H'},{k:'Ouro',v:'24 Quilates'}] },
  { nome:'Nreal Light Or Edition', marca:'Nreal', categoria:'VIRTUAL', preco:2900, descricao:'Os óculos AR mais acessíveis do mercado premium. Armação em alumínio ultraleve com hastes banhadas a ouro 24k.', imagem:'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&q=80', estoque:true, destaque:false, novo:false, specs:[{k:'Display',v:'1080p'},{k:'Brilho',v:'700 nits'},{k:'Peso',v:'106g'},{k:'Ouro',v:'24 Quilates'}] },
]

await Produto.insertMany(produtos)
console.log(`\n🎉 ${produtos.length} produtos inseridos com sucesso!`)
console.log(`📊 Distribuição:`)
const cats = {}
produtos.forEach(p => { cats[p.categoria] = (cats[p.categoria]||0)+1 })
Object.entries(cats).forEach(([cat, n]) => console.log(`   ${cat}: ${n} produtos`))

await mongoose.disconnect()
process.exit()